In [58]:
def temper(x):
    x ^^= x >> 11
    x ^^= (x << 7) & 0x9D2C5680
    x ^^= (x << 15) & 0xEFC60000
    x ^^= x >> 18
    return x

In [59]:
def set_row(mm, num, row):
    for ii in range(32):
        mm[row, ii] = (num & (1 << ii)) != 0

A = Matrix(GF(2), 32, 32)
B = Matrix(GF(2), 32, 32)

import random
for row in range(32):
    cand = random.randint(0, 2**32-1)
    set_row(A, cand, row)
    set_row(B, temper(cand), row)

In [60]:
A.rank()

32

In [61]:
T = (A^-1) * B
T_inv = T^-1

In [62]:
print(T_inv.str())

[1 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1]
[0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0]
[0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1]
[0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0]
[0 0 0 0 1

In [63]:
def col_to_num(mm, col):
    res = 0
    for ii in range(32):
        if mm[ii, col]:
            res |= 1 << ii
    return res

In [67]:
for col in range(32):
    print(hex(col_to_num(T_inv, col)) + ',')

0x22440881,
0x44081122,
0x89022200,
0x10244489,
0x64c89830,
0x48911020,
0x133640c5,
0x2204889,
0x4889120,
0x81130000,
0x12044489,
0x22400880,
0x44001120,
0x89122204,
0x10044481,
0x64889820,
0x48111000,
0x12364085,
0x244808,
0x889020,
0x89030204,
0x2244081,
0x2400080,
0x4800100,
0x9120204,
0x12000400,
0x64881820,
0x48101000,
0x12244081,
0x20004000,
0x40008000,
0x89130204,
